### ISSUE TITLE
[Food for thought] Consolidate jobs notifications (?)

### ISSUE THREAD

**Issue by raquezha** [raquezha/nuecagram#10]
**Is your feature request related to a problem? Please describe.**
Not really an issue but overwhelming influx of notification receive

**Describe the solution you'd like**
A robust way to receive notification if you have to many jobs

**Describe alternatives you've considered**
Don't change it the code, just reconfigure your jobs and limit it a minimum amount

**Additional context**
Too much notification in a span of minutes
![jobs](https://github.com/raquezha/nuecagram/assets/9584016/129cd05b-e98a-48c2-a2a5-d715d7c00d98)

**Comment by raquezha** [comment]
Should look how integram implement it. Basically 1 Job or Pipeline consumes only 1 Message and updates it when there's something to update

**Comment by NewblyAaron** [comment]
Probably can use Telegram's API call [messages.editMessage](https://core.telegram.org/method/messages.editMessage) to edit the message.

For tracking each job though, there needs some sort of storage to store its job ID and message ID. SQLite could be used to have some persistence if ever the server goes down, or if that's not a problem, just implementing a list storing such in the program should work.

The idea is whenever a job event gets sent:
- If it's a new job, it sends a new message, save the data we need to track it, and put it in the list.
- If it's a job that's already in the list, it gets its message ID and edit the message with the relevant information from the event.

Once a job completes (finished successfully, error, etc.), it removes it from the list.
