### ISSUE TITLE
Incorrect Message Displayed After Tag Deletion

### ISSUE THREAD

**Issue by raquezha** [raquezha/nuecagram#28]
**Description:**

When a tag is created in the Nuecagram application, the system correctly acknowledges that a new tag has been pushed. However, when a tag is deleted, the application incorrectly displays a message stating that a new tag was pushed, instead of confirming the deletion of the tag.

**Steps to Reproduce:**

1. Create a new tag in the application.
2. Verify that the application shows the correct message, confirming the tag has been pushed.
3. Delete the tag.
4. Observe the message displayed. The application still indicates that a new tag has been pushed rather than confirming the deletion of the tag.

**Expected behavior:**

When a tag is deleted, the application should display a confirmation message indicating that the tag was successfully deleted.

**Actual behavior:**

Instead of confirming the tag deletion, the application incorrectly shows a message stating that a new tag was pushed, even though a tag was deleted.

**Screenshots/Screen Recordings (Optional):**

* Include screenshots or screen recordings of any relevant error messages or unexpected behavior.

![image](https://github.com/user-attachments/assets/72bf9fed-664a-4818-91b9-e8c80b06785f)

**Comment by NewblyAaron** [comment]
Noticed that the response's `after` value zeroes out when deleting a tag. I'm guessing this is the commit ID. 

![image](https://github.com/user-attachments/assets/c266aaf8-f686-4699-ab42-d4454b840c48)

Maybe check if `after` value is all zero?

**Comment by raquezha** [comment]
Nice. then when can use `before` and `after` to check if tag is `created`, `deleted` and even `updated`.

Something like this:

```kotlin
fun handleTag(): String {
    val beforeSha = "getBeforeSha()"
    val afterSha = "getAfterSha()" 
    return when {
        beforeSha.isNullHash() -> "Tag {tag_name} created"
        afterSha.isNullHash() -> "Tag {tag_name} deleted"
        else -> "Tag {tag_name} updated."
    }
}

fun String.isNullHash(): Boolean {
    return this == "0000000000000000000000000000000000000000"
}
```
